id: P4FBF85EA
initial_creation_type: input
source_metadata:
  title: Alak Zenkar Rinpoche
  language: it
  description: 'Texts by and about the great scholar Alak Zenkar Rinpoche Thupten
    Nyima (a lags gzan dkar thub bstan nyi ma, b.1943):'
  volume:
    9ce1519ed93f4400840bbbd90cc7902c:
      title: Biography of Jamgön Kongtrul Lodrö Thaye
      parent: Biography
    3f557e6242274dd1b7cc59efdf44d540:
      title: Biography of Jamyang Khyentse Wangpo
      parent: Biography
    8c1f0dfddc6b4a17bfd27fe8aad12834:
      title: Biography of Patrul Rinpoche
      parent: Biography
    e696cdfb4eff4b73837021f682279f11:
      title: Biography of Shechen Gyaltsab Gyurme Pema Namgyal
      parent: Biography
    00c2be87c43e4c2dbd48c4507e0edf38:
      title: Brief Biography of Drakkar Lobzang Palden
      parent: Biography
    fd1bb3fdd20b4577a209d30d007b9f91:
      title: Brief Biography of Kharlek Tulku Pema Kunzang Rangdrol
      parent: Biography
    d62a23878e4b42c482455e10c666e15a:
      title: Brief Biography of Tāranātha
      parent: Biography
    9361056d7f394e6982a55de27f4dd0c0:
      title: A Brief Presentation of the Nine Vehicles
      parent: Buddhist Philosophy
    c1c25b85f9df46cc809c467ee06a8913:
      title: Long Life Prayer for Alak Zenkar Rinpoche
      parent: Long Life Prayers
    5e7593cc64db4d3985617cb8cdf91db1:
      title: Long Life Prayer for Patrick Gaffney (Yeshé Wangyal)
      parent: Long Life Prayers
    d0780423d8fd4e4c818dbf3577e541b7:
      title: Prayer for the Long Life of Alak Zenkar Rinpoche, the Incarnation of
        Do Khyentsé Yeshé Dorjé
      parent: Long Life Prayers
    b2696bb2c2a742dd9a41fa96dc39746e:
      title: 'Bodhicaryāvatāra: Teachings and Overview'
      parent: Oral Teachings
    7ac834cbad3e4e69a354af4cc7be7119:
      title: Light from the Wisdom Sun
      parent: Prayers and Practices
    9dc77886f2aa4794b98ca2928570eff4:
      title: A Prayer for the Swift Rebirth of Tenpai Nyima Rinpoche
      parent: Swift Rebirth Prayers
    48e788c78b98487da50a03ebf8cca677:
      title: Prayer for Swift Rebirth of the Fourth Dodrupchen Rinpoche
      parent: Swift Rebirth Prayers
created_at: '2022-02-28T22:37:59.746429'
last_modified_at: '2022-02-28T22:37:59.746432'
